algoritmo "campeonatodevolei"

var
altura:real
idade:inteiro

inicio

//Entrada
escreval("Quantos metros de altura você tem? ")
leia(altura)
escreval("Quantos anos você tem? ")
leia(idade)

//Processamento
se((altura>=1.75) e (idade>=18))entao
   escreval("Você pode participar do campeonato de vôlei!")

senao
   escreval("Você não pode participar do campeonato de vôlei!")
   
fimse




fimalgoritmo
