algoritmo "melhorescolaribeirao"
// Função : Dizer qual é a melhor escola localizada em Ribeirão Pires!
// Autor : Gabriel Miranda
// Data : 13/09/2020
// Seção de Declarações 
var
escola: CARACTERE

inicio
//Processamento
escola<- ""
   enquanto (escola<>"Escola Etec MCM")faca
    escreval("Qual é a melhor escola de toda Ribeirão Pires: ")
    leia(escola)
   fimenquanto

fimalgoritmo
