algoritmo "somarnumeros0"
// Função : Somar números até digitar o número 0!
// Autor : Gabriel Miranda
// Data : 13/09/2020
// Seção de Declarações 
var
soma, numero: inteiro



inicio


//Processamento
numero<-1
soma<- 0
 enquanto (numero<>0)faca
    escreval("Digite um número: ")
     leia(numero)
soma<- soma+numero
 fimenquanto
escreval("A soma total dos números é: ",soma)





fimalgoritmo
