algoritmo "soma10numeros"
// Função : Calcular a soma de 10 números!
// Autor : Gabriel Miranda
// Data : 13/09/2020
// Seção de Declarações 
var
contador,soma,numero:INTEIRO


inicio


//Processamento
soma<-0
para contador de 1 ate 10 passo 1 faca
  escreval("Digite um número: ")
   leia(numero)
  soma<-soma+numero
fimpara
escreval("O resultado da soma dos números é de: ",soma)

fimalgoritmo



