algoritmo "tabuada"
// Função : Exibir a tabuada dos números escolhas pelo usuário!
// Autor : Gabriel Miranda
// Data : 13/09/2020
// Seção de Declarações 
var
contador,valor,resultado: INTEIRO

inicio
//Entrada
escreval("Escolha um número : ")
leia(valor)

//Processamento
 para contador de 1 ate 10 faca
  resultado<-(valor*contador)
  escreval(valor," X",contador," =",resultado)
 fimpara



fimalgoritmo
